name: CI

on: 
  pull_request:
  - master
  - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: docker://php:7.3
        
  test:
    steps:
      - name: run phpunit
        run: php vendor/bin/phpunit.php
