name: CI

on: 
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: docker://php:7.3
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run phpunit
        run: php vendor/bin/phpunit.php
