name: CI

on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        uses: docker://php:7.3
      - name: Install repository
        uses: actions/checkout@v1
      - name: Install Composer
        run: curl https://getcomposer.org/installer | php
      - name: Install dependencies 
        run: php composer.phar install
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: run phpunit
        run: php vendor/bin/phpunit.php
