name: Build and Test

on: 
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Repository
        uses: actions/checkout@v1
      - name: Install Dependencies 
        run: composer install
      - name: Setup Testing DB
        run: composer run-script setup-testdb
      - name: Run Tests
        run: php vendor/bin/phpunit
